language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
script:
  - vendor/bin/behat
  - vendor/bin/phpspec run
  - vendor/bin/psalm
